### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by peter279k** [PayCrypto/crypto-monitor#3]
As title.
@Bilge, I use the ```Porter``` to implement the CoinAPI.

If possible, can you help me reviewing the code in this repository?

Thanks and I will appreciate your help.

**Comment by Bilge** [comment]
Absolutely, I'll take a look at some point today. Is there a PR or is it the entire repository?

**Comment by peter279k** [comment]
This is our initialized repository.
If possible, I would like you review the entire repository.

Thanks.

**Comment by Bilge** [comment]
I can definitely see a few problems but it's difficult to review a repository. GitHub only supports reviewing PRs. Maybe you could turn it into a PR somehow? If you create a branch with an empty commit and then create a PR merging master into that branch, that should work.

**Comment by peter279k** [comment]
@Bilge, if possible, can you fork the repo and send the PR?

Thanks.

**Comment by Bilge** [comment]
I'm not going to write any code, just write a review, so it would make sense for you to create the PR so you can make changes to the code (and have it re-reviewed if necessary).

**Comment by peter279k** [comment]
Please visit this [link](https://github.com/PayCrypto/crypto-monitor/commit/4246a9949767400878186f217bed63d321efe33e) to do the code review.

Thanks.

**Comment by peter279k** [comment]
It squashes the commits and merges in this PR #6 .
This issue is closed.
